name: slivka
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=19
  - click=7
  - flask=1
  - frozendict=1
  - gunicorn
  - jsonschema=3
  - nose=1.3
  - pip>=18.0
  - python=3.7
  - pymongo=3
  - pyyaml=5
  - pyzmq=19
  - requests=2
  - setuptools>=40.4
  - simplejson=3
  - werkzeug=1
