name: slivka
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs>=19
  - click>=7.0
  - flask>=1.0
  - frozendict>=1.2
  - gunicorn>=19.9
  - jsonschema>=2.6
  - markupsafe>=1.0
  - nose>=1.3.7
  - pip>=18.0
  - python=3.7
  - pymongo>=3.7
  - pyyaml>=3.13
  - pyzmq>=17.1
  - requests>=2.13
  - setuptools>=40.4
  - simplejson>=3.16
  - werkzeug>=0.15
