{% set version="0.8.1b1" %}

package:
  name: slivka
  version: {{ version }}

source:
  git_url: ../
  git_depth: 1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install -vv --no-deps ."
  entry_points:
    - slivka=slivka.cli:main

channels:
  - conda-forge
  - defaults

requirements:
  host:
    - python>=3.7,<3.11
  run:
    - attrs>=19
    - click>=7.0
    - flask>=2.0
    - frozendict>=1.2
    - jsonschema>=3.0
    - markupsafe>=1.0
    - mongomock>=3.18
    - nose>=1.3.7
    - pip>=18.0
    - python>=3.7,<3.11
    - pymongo>=3.7
    - pyyaml>=5.4
    - pyzmq>=19.0
    - simplejson>=3.16
    - werkzeug>=1.0,<2.3.0

tests:
  imports:
    - slivka
