{% set version="0.8b16" %}

package:
  name: slivka
  version: {{ version }}

source:
  git_url: ../
  git_rev: dev

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install -vv --no-deps ."
  entry_points:
    - slivka=slivka.cli:main

channels:
  - conda-forge
  - defaults

requirements:
  host:
    - python>=3.7
  run:
    - attrs>=19
    - click>=7.0
    - flask>=1.0,<2.0
    - frozendict>=1.2
    - jsonschema>=2.6
    - markupsafe>=1.0
    - mongomock>=3.18
    - nose>=1.3
    - pip>=18.0
    - python>=3.7
    - pymongo>=3.7
    - pyyaml>=5.4
    - pyzmq>=17.1
    - simplejson>=3.16
    - werkzeug>=0.15

tests:
  imports:
    - slivka
